name: Adam Silver | UX consultant. Engineering. Design. Strategy. Making things simple and human. Based in London.
markdown: kramdown
permalink: /articles/:title/
url: http://adamsilver.io
include: ['_pages']