name: "Adam Silver: interaction designer and interface developer from London, UK"
markdown: kramdown
permalink: /articles/:title/
url: https://adamsilver.io
include: ['_pages']
description: I'm Adam Silver, an interaction designer who codes simple and inclusive digital services, products and websites.
future: true
exclude: ['node_modules', 'Gruntfile.js']
sass:
  sass_dir: assets/_sass