name: Adam Silver, Front-end web developer, based in London
markdown: redcarpet
highlighter: pygments
permalink: ./:title
exclude: [adamsilver.sublime-project, adamsilver.sublime-workspace]
url: http://adamsilver.github.io