name: Adam Silver, Frontend developer based in London
markdown: redcarpet
highlighter: pygments
permalink: /articles/:title/
url: http://adamsilver.github.io
include: ['_pages']
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]