name: "Adam Silver: designer and interface developer from London, UK"
markdown: kramdown
permalink: /articles/:title/
url: https://adamsilver.io
include: ['_pages']
description: Hello, I am Adam Silver, I specialise in UX, Front-end Engineering and Strategy. I help companies and people design simple, human and inclusive websites. Based in London.
future: true
exclude: ['node_modules', 'Gruntfile.js']