name: Adam Silver, Front end developer, based in London
markdown: redcarpet
highlighter: pygments
permalink: /articles/:title/
exclude: [adamsilver.sublime-project, adamsilver.sublime-workspace]
url: http://adamsilver.github.io
include: ['_pages']